// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sl-mac-pdu-tag.proto

#include "sl-mac-pdu-tag.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_sl_2dsfnsf_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_sl_2dsfnsf_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_SfnSfProto;
}  // namespace protobuf_sl_2dsfnsf_2eproto
namespace ns3 {
class NrSlMacPduTagProtoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<NrSlMacPduTagProto>
      _instance;
} _NrSlMacPduTagProto_default_instance_;
}  // namespace ns3
namespace protobuf_sl_2dmac_2dpdu_2dtag_2eproto {
static void InitDefaultsNrSlMacPduTagProto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ns3::_NrSlMacPduTagProto_default_instance_;
    new (ptr) ::ns3::NrSlMacPduTagProto();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ns3::NrSlMacPduTagProto::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_NrSlMacPduTagProto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsNrSlMacPduTagProto}, {
      &protobuf_sl_2dsfnsf_2eproto::scc_info_SfnSfProto.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_NrSlMacPduTagProto.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ns3::NrSlMacPduTagProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ns3::NrSlMacPduTagProto, m_rnti_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ns3::NrSlMacPduTagProto, m_symstart_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ns3::NrSlMacPduTagProto, m_numsym_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ns3::NrSlMacPduTagProto, m_tbsize_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ns3::NrSlMacPduTagProto, m_dstl2id_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::ns3::NrSlMacPduTagProto, m_sfnsf_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ns3::NrSlMacPduTagProto)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ns3::_NrSlMacPduTagProto_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "sl-mac-pdu-tag.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\024sl-mac-pdu-tag.proto\022\003ns3\032\016sl-sfnsf.pr"
      "oto\"\221\001\n\022NrSlMacPduTagProto\022\016\n\006m_rnti\030\001 \001"
      "(\r\022\022\n\nm_symStart\030\002 \001(\r\022\020\n\010m_numSym\030\003 \001(\r"
      "\022\020\n\010m_tbSize\030\004 \001(\r\022\021\n\tm_dstL2Id\030\005 \001(\r\022 \n"
      "\007m_sfnSf\030\006 \001(\0132\017.ns3.SfnSfProtob\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 199);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "sl-mac-pdu-tag.proto", &protobuf_RegisterTypes);
  ::protobuf_sl_2dsfnsf_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_sl_2dmac_2dpdu_2dtag_2eproto
namespace ns3 {

// ===================================================================

void NrSlMacPduTagProto::InitAsDefaultInstance() {
  ::ns3::_NrSlMacPduTagProto_default_instance_._instance.get_mutable()->m_sfnsf_ = const_cast< ::ns3::SfnSfProto*>(
      ::ns3::SfnSfProto::internal_default_instance());
}
void NrSlMacPduTagProto::clear_m_sfnsf() {
  if (GetArenaNoVirtual() == NULL && m_sfnsf_ != NULL) {
    delete m_sfnsf_;
  }
  m_sfnsf_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int NrSlMacPduTagProto::kMRntiFieldNumber;
const int NrSlMacPduTagProto::kMSymStartFieldNumber;
const int NrSlMacPduTagProto::kMNumSymFieldNumber;
const int NrSlMacPduTagProto::kMTbSizeFieldNumber;
const int NrSlMacPduTagProto::kMDstL2IdFieldNumber;
const int NrSlMacPduTagProto::kMSfnSfFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

NrSlMacPduTagProto::NrSlMacPduTagProto()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_sl_2dmac_2dpdu_2dtag_2eproto::scc_info_NrSlMacPduTagProto.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:ns3.NrSlMacPduTagProto)
}
NrSlMacPduTagProto::NrSlMacPduTagProto(const NrSlMacPduTagProto& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_m_sfnsf()) {
    m_sfnsf_ = new ::ns3::SfnSfProto(*from.m_sfnsf_);
  } else {
    m_sfnsf_ = NULL;
  }
  ::memcpy(&m_rnti_, &from.m_rnti_,
    static_cast<size_t>(reinterpret_cast<char*>(&m_dstl2id_) -
    reinterpret_cast<char*>(&m_rnti_)) + sizeof(m_dstl2id_));
  // @@protoc_insertion_point(copy_constructor:ns3.NrSlMacPduTagProto)
}

void NrSlMacPduTagProto::SharedCtor() {
  ::memset(&m_sfnsf_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&m_dstl2id_) -
      reinterpret_cast<char*>(&m_sfnsf_)) + sizeof(m_dstl2id_));
}

NrSlMacPduTagProto::~NrSlMacPduTagProto() {
  // @@protoc_insertion_point(destructor:ns3.NrSlMacPduTagProto)
  SharedDtor();
}

void NrSlMacPduTagProto::SharedDtor() {
  if (this != internal_default_instance()) delete m_sfnsf_;
}

void NrSlMacPduTagProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* NrSlMacPduTagProto::descriptor() {
  ::protobuf_sl_2dmac_2dpdu_2dtag_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_sl_2dmac_2dpdu_2dtag_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const NrSlMacPduTagProto& NrSlMacPduTagProto::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_sl_2dmac_2dpdu_2dtag_2eproto::scc_info_NrSlMacPduTagProto.base);
  return *internal_default_instance();
}


void NrSlMacPduTagProto::Clear() {
// @@protoc_insertion_point(message_clear_start:ns3.NrSlMacPduTagProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && m_sfnsf_ != NULL) {
    delete m_sfnsf_;
  }
  m_sfnsf_ = NULL;
  ::memset(&m_rnti_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&m_dstl2id_) -
      reinterpret_cast<char*>(&m_rnti_)) + sizeof(m_dstl2id_));
  _internal_metadata_.Clear();
}

bool NrSlMacPduTagProto::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ns3.NrSlMacPduTagProto)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // uint32 m_rnti = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &m_rnti_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 m_symStart = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &m_symstart_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 m_numSym = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &m_numsym_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 m_tbSize = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &m_tbsize_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // uint32 m_dstL2Id = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &m_dstl2id_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .ns3.SfnSfProto m_sfnSf = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_m_sfnsf()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ns3.NrSlMacPduTagProto)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ns3.NrSlMacPduTagProto)
  return false;
#undef DO_
}

void NrSlMacPduTagProto::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ns3.NrSlMacPduTagProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 m_rnti = 1;
  if (this->m_rnti() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->m_rnti(), output);
  }

  // uint32 m_symStart = 2;
  if (this->m_symstart() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(2, this->m_symstart(), output);
  }

  // uint32 m_numSym = 3;
  if (this->m_numsym() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(3, this->m_numsym(), output);
  }

  // uint32 m_tbSize = 4;
  if (this->m_tbsize() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->m_tbsize(), output);
  }

  // uint32 m_dstL2Id = 5;
  if (this->m_dstl2id() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(5, this->m_dstl2id(), output);
  }

  // .ns3.SfnSfProto m_sfnSf = 6;
  if (this->has_m_sfnsf()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6, this->_internal_m_sfnsf(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:ns3.NrSlMacPduTagProto)
}

::google::protobuf::uint8* NrSlMacPduTagProto::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:ns3.NrSlMacPduTagProto)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 m_rnti = 1;
  if (this->m_rnti() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->m_rnti(), target);
  }

  // uint32 m_symStart = 2;
  if (this->m_symstart() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(2, this->m_symstart(), target);
  }

  // uint32 m_numSym = 3;
  if (this->m_numsym() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(3, this->m_numsym(), target);
  }

  // uint32 m_tbSize = 4;
  if (this->m_tbsize() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->m_tbsize(), target);
  }

  // uint32 m_dstL2Id = 5;
  if (this->m_dstl2id() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(5, this->m_dstl2id(), target);
  }

  // .ns3.SfnSfProto m_sfnSf = 6;
  if (this->has_m_sfnsf()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->_internal_m_sfnsf(), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ns3.NrSlMacPduTagProto)
  return target;
}

size_t NrSlMacPduTagProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ns3.NrSlMacPduTagProto)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .ns3.SfnSfProto m_sfnSf = 6;
  if (this->has_m_sfnsf()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *m_sfnsf_);
  }

  // uint32 m_rnti = 1;
  if (this->m_rnti() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->m_rnti());
  }

  // uint32 m_symStart = 2;
  if (this->m_symstart() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->m_symstart());
  }

  // uint32 m_numSym = 3;
  if (this->m_numsym() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->m_numsym());
  }

  // uint32 m_tbSize = 4;
  if (this->m_tbsize() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->m_tbsize());
  }

  // uint32 m_dstL2Id = 5;
  if (this->m_dstl2id() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->m_dstl2id());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NrSlMacPduTagProto::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ns3.NrSlMacPduTagProto)
  GOOGLE_DCHECK_NE(&from, this);
  const NrSlMacPduTagProto* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const NrSlMacPduTagProto>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ns3.NrSlMacPduTagProto)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ns3.NrSlMacPduTagProto)
    MergeFrom(*source);
  }
}

void NrSlMacPduTagProto::MergeFrom(const NrSlMacPduTagProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ns3.NrSlMacPduTagProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_m_sfnsf()) {
    mutable_m_sfnsf()->::ns3::SfnSfProto::MergeFrom(from.m_sfnsf());
  }
  if (from.m_rnti() != 0) {
    set_m_rnti(from.m_rnti());
  }
  if (from.m_symstart() != 0) {
    set_m_symstart(from.m_symstart());
  }
  if (from.m_numsym() != 0) {
    set_m_numsym(from.m_numsym());
  }
  if (from.m_tbsize() != 0) {
    set_m_tbsize(from.m_tbsize());
  }
  if (from.m_dstl2id() != 0) {
    set_m_dstl2id(from.m_dstl2id());
  }
}

void NrSlMacPduTagProto::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ns3.NrSlMacPduTagProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NrSlMacPduTagProto::CopyFrom(const NrSlMacPduTagProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ns3.NrSlMacPduTagProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NrSlMacPduTagProto::IsInitialized() const {
  return true;
}

void NrSlMacPduTagProto::Swap(NrSlMacPduTagProto* other) {
  if (other == this) return;
  InternalSwap(other);
}
void NrSlMacPduTagProto::InternalSwap(NrSlMacPduTagProto* other) {
  using std::swap;
  swap(m_sfnsf_, other->m_sfnsf_);
  swap(m_rnti_, other->m_rnti_);
  swap(m_symstart_, other->m_symstart_);
  swap(m_numsym_, other->m_numsym_);
  swap(m_tbsize_, other->m_tbsize_);
  swap(m_dstl2id_, other->m_dstl2id_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata NrSlMacPduTagProto::GetMetadata() const {
  protobuf_sl_2dmac_2dpdu_2dtag_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_sl_2dmac_2dpdu_2dtag_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ns3
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::ns3::NrSlMacPduTagProto* Arena::CreateMaybeMessage< ::ns3::NrSlMacPduTagProto >(Arena* arena) {
  return Arena::CreateInternal< ::ns3::NrSlMacPduTagProto >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
