// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/sl-sfnsf.proto

#include "proto/sl-sfnsf.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
namespace ns3 {
class SfnSfProtoDefaultTypeInternal {
 public:
  ::PROTOBUF_NAMESPACE_ID::internal::ExplicitlyConstructed<SfnSfProto> _instance;
} _SfnSfProto_default_instance_;
}  // namespace ns3
static void InitDefaultsscc_info_SfnSfProto_proto_2fsl_2dsfnsf_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ns3::_SfnSfProto_default_instance_;
    new (ptr) ::ns3::SfnSfProto();
    ::PROTOBUF_NAMESPACE_ID::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ns3::SfnSfProto::InitAsDefaultInstance();
}

::PROTOBUF_NAMESPACE_ID::internal::SCCInfo<0> scc_info_SfnSfProto_proto_2fsl_2dsfnsf_2eproto =
    {{ATOMIC_VAR_INIT(::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase::kUninitialized), 0, 0, InitDefaultsscc_info_SfnSfProto_proto_2fsl_2dsfnsf_2eproto}, {}};

static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_proto_2fsl_2dsfnsf_2eproto[1];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_proto_2fsl_2dsfnsf_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_proto_2fsl_2dsfnsf_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_proto_2fsl_2dsfnsf_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ns3::SfnSfProto, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ns3::SfnSfProto, m_framenum_),
  PROTOBUF_FIELD_OFFSET(::ns3::SfnSfProto, m_subframenum_),
  PROTOBUF_FIELD_OFFSET(::ns3::SfnSfProto, m_slotnum_),
  PROTOBUF_FIELD_OFFSET(::ns3::SfnSfProto, m_numerology_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ns3::SfnSfProto)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::ns3::_SfnSfProto_default_instance_),
};

const char descriptor_table_protodef_proto_2fsl_2dsfnsf_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\024proto/sl-sfnsf.proto\022\003ns3\"`\n\nSfnSfProt"
  "o\022\022\n\nm_frameNum\030\001 \001(\r\022\025\n\rm_subframeNum\030\002"
  " \001(\r\022\021\n\tm_slotNum\030\003 \001(\r\022\024\n\014m_numerology\030"
  "\004 \001(\005b\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_proto_2fsl_2dsfnsf_2eproto_deps[1] = {
};
static ::PROTOBUF_NAMESPACE_ID::internal::SCCInfoBase*const descriptor_table_proto_2fsl_2dsfnsf_2eproto_sccs[1] = {
  &scc_info_SfnSfProto_proto_2fsl_2dsfnsf_2eproto.base,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_proto_2fsl_2dsfnsf_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fsl_2dsfnsf_2eproto = {
  false, false, descriptor_table_protodef_proto_2fsl_2dsfnsf_2eproto, "proto/sl-sfnsf.proto", 133,
  &descriptor_table_proto_2fsl_2dsfnsf_2eproto_once, descriptor_table_proto_2fsl_2dsfnsf_2eproto_sccs, descriptor_table_proto_2fsl_2dsfnsf_2eproto_deps, 1, 0,
  schemas, file_default_instances, TableStruct_proto_2fsl_2dsfnsf_2eproto::offsets,
  file_level_metadata_proto_2fsl_2dsfnsf_2eproto, 1, file_level_enum_descriptors_proto_2fsl_2dsfnsf_2eproto, file_level_service_descriptors_proto_2fsl_2dsfnsf_2eproto,
};

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_proto_2fsl_2dsfnsf_2eproto = (static_cast<void>(::PROTOBUF_NAMESPACE_ID::internal::AddDescriptors(&descriptor_table_proto_2fsl_2dsfnsf_2eproto)), true);
namespace ns3 {

// ===================================================================

void SfnSfProto::InitAsDefaultInstance() {
}
class SfnSfProto::_Internal {
 public:
};

SfnSfProto::SfnSfProto(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:ns3.SfnSfProto)
}
SfnSfProto::SfnSfProto(const SfnSfProto& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::memcpy(&m_framenum_, &from.m_framenum_,
    static_cast<size_t>(reinterpret_cast<char*>(&m_numerology_) -
    reinterpret_cast<char*>(&m_framenum_)) + sizeof(m_numerology_));
  // @@protoc_insertion_point(copy_constructor:ns3.SfnSfProto)
}

void SfnSfProto::SharedCtor() {
  ::memset(&m_framenum_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&m_numerology_) -
      reinterpret_cast<char*>(&m_framenum_)) + sizeof(m_numerology_));
}

SfnSfProto::~SfnSfProto() {
  // @@protoc_insertion_point(destructor:ns3.SfnSfProto)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void SfnSfProto::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void SfnSfProto::ArenaDtor(void* object) {
  SfnSfProto* _this = reinterpret_cast< SfnSfProto* >(object);
  (void)_this;
}
void SfnSfProto::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void SfnSfProto::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const SfnSfProto& SfnSfProto::default_instance() {
  ::PROTOBUF_NAMESPACE_ID::internal::InitSCC(&::scc_info_SfnSfProto_proto_2fsl_2dsfnsf_2eproto.base);
  return *internal_default_instance();
}


void SfnSfProto::Clear() {
// @@protoc_insertion_point(message_clear_start:ns3.SfnSfProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&m_framenum_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&m_numerology_) -
      reinterpret_cast<char*>(&m_framenum_)) + sizeof(m_numerology_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* SfnSfProto::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  ::PROTOBUF_NAMESPACE_ID::Arena* arena = GetArena(); (void)arena;
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 m_frameNum = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          m_framenum_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 m_subframeNum = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          m_subframenum_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 m_slotNum = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          m_slotnum_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 m_numerology = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          m_numerology_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* SfnSfProto::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ns3.SfnSfProto)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 m_frameNum = 1;
  if (this->m_framenum() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_m_framenum(), target);
  }

  // uint32 m_subframeNum = 2;
  if (this->m_subframenum() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(2, this->_internal_m_subframenum(), target);
  }

  // uint32 m_slotNum = 3;
  if (this->m_slotnum() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_m_slotnum(), target);
  }

  // int32 m_numerology = 4;
  if (this->m_numerology() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_m_numerology(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ns3.SfnSfProto)
  return target;
}

size_t SfnSfProto::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ns3.SfnSfProto)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 m_frameNum = 1;
  if (this->m_framenum() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_m_framenum());
  }

  // uint32 m_subframeNum = 2;
  if (this->m_subframenum() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_m_subframenum());
  }

  // uint32 m_slotNum = 3;
  if (this->m_slotnum() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_m_slotnum());
  }

  // int32 m_numerology = 4;
  if (this->m_numerology() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_m_numerology());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void SfnSfProto::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ns3.SfnSfProto)
  GOOGLE_DCHECK_NE(&from, this);
  const SfnSfProto* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<SfnSfProto>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ns3.SfnSfProto)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ns3.SfnSfProto)
    MergeFrom(*source);
  }
}

void SfnSfProto::MergeFrom(const SfnSfProto& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ns3.SfnSfProto)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.m_framenum() != 0) {
    _internal_set_m_framenum(from._internal_m_framenum());
  }
  if (from.m_subframenum() != 0) {
    _internal_set_m_subframenum(from._internal_m_subframenum());
  }
  if (from.m_slotnum() != 0) {
    _internal_set_m_slotnum(from._internal_m_slotnum());
  }
  if (from.m_numerology() != 0) {
    _internal_set_m_numerology(from._internal_m_numerology());
  }
}

void SfnSfProto::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ns3.SfnSfProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SfnSfProto::CopyFrom(const SfnSfProto& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ns3.SfnSfProto)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SfnSfProto::IsInitialized() const {
  return true;
}

void SfnSfProto::InternalSwap(SfnSfProto* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SfnSfProto, m_numerology_)
      + sizeof(SfnSfProto::m_numerology_)
      - PROTOBUF_FIELD_OFFSET(SfnSfProto, m_framenum_)>(
          reinterpret_cast<char*>(&m_framenum_),
          reinterpret_cast<char*>(&other->m_framenum_));
}

::PROTOBUF_NAMESPACE_ID::Metadata SfnSfProto::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ns3
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ns3::SfnSfProto* Arena::CreateMaybeMessage< ::ns3::SfnSfProto >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ns3::SfnSfProto >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
