// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/sl-sfnsf.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_proto_2fsl_2dsfnsf_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_proto_2fsl_2dsfnsf_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_proto_2fsl_2dsfnsf_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_proto_2fsl_2dsfnsf_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_proto_2fsl_2dsfnsf_2eproto;
namespace ns3 {
class SfnSfProto;
class SfnSfProtoDefaultTypeInternal;
extern SfnSfProtoDefaultTypeInternal _SfnSfProto_default_instance_;
}  // namespace ns3
PROTOBUF_NAMESPACE_OPEN
template<> ::ns3::SfnSfProto* Arena::CreateMaybeMessage<::ns3::SfnSfProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ns3 {

// ===================================================================

class SfnSfProto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ns3.SfnSfProto) */ {
 public:
  inline SfnSfProto() : SfnSfProto(nullptr) {};
  virtual ~SfnSfProto();

  SfnSfProto(const SfnSfProto& from);
  SfnSfProto(SfnSfProto&& from) noexcept
    : SfnSfProto() {
    *this = ::std::move(from);
  }

  inline SfnSfProto& operator=(const SfnSfProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline SfnSfProto& operator=(SfnSfProto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SfnSfProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SfnSfProto* internal_default_instance() {
    return reinterpret_cast<const SfnSfProto*>(
               &_SfnSfProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SfnSfProto& a, SfnSfProto& b) {
    a.Swap(&b);
  }
  inline void Swap(SfnSfProto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SfnSfProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SfnSfProto* New() const final {
    return CreateMaybeMessage<SfnSfProto>(nullptr);
  }

  SfnSfProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SfnSfProto>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SfnSfProto& from);
  void MergeFrom(const SfnSfProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SfnSfProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ns3.SfnSfProto";
  }
  protected:
  explicit SfnSfProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_proto_2fsl_2dsfnsf_2eproto);
    return ::descriptor_table_proto_2fsl_2dsfnsf_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMFrameNumFieldNumber = 1,
    kMSubframeNumFieldNumber = 2,
    kMSlotNumFieldNumber = 3,
    kMNumerologyFieldNumber = 4,
  };
  // uint32 m_frameNum = 1;
  void clear_m_framenum();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_framenum() const;
  void set_m_framenum(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_framenum() const;
  void _internal_set_m_framenum(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_subframeNum = 2;
  void clear_m_subframenum();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_subframenum() const;
  void set_m_subframenum(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_subframenum() const;
  void _internal_set_m_subframenum(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_slotNum = 3;
  void clear_m_slotnum();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_slotnum() const;
  void set_m_slotnum(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_slotnum() const;
  void _internal_set_m_slotnum(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // int32 m_numerology = 4;
  void clear_m_numerology();
  ::PROTOBUF_NAMESPACE_ID::int32 m_numerology() const;
  void set_m_numerology(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_m_numerology() const;
  void _internal_set_m_numerology(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:ns3.SfnSfProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_framenum_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_subframenum_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_slotnum_;
  ::PROTOBUF_NAMESPACE_ID::int32 m_numerology_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_proto_2fsl_2dsfnsf_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SfnSfProto

// uint32 m_frameNum = 1;
inline void SfnSfProto::clear_m_framenum() {
  m_framenum_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SfnSfProto::_internal_m_framenum() const {
  return m_framenum_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SfnSfProto::m_framenum() const {
  // @@protoc_insertion_point(field_get:ns3.SfnSfProto.m_frameNum)
  return _internal_m_framenum();
}
inline void SfnSfProto::_internal_set_m_framenum(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_framenum_ = value;
}
inline void SfnSfProto::set_m_framenum(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_framenum(value);
  // @@protoc_insertion_point(field_set:ns3.SfnSfProto.m_frameNum)
}

// uint32 m_subframeNum = 2;
inline void SfnSfProto::clear_m_subframenum() {
  m_subframenum_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SfnSfProto::_internal_m_subframenum() const {
  return m_subframenum_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SfnSfProto::m_subframenum() const {
  // @@protoc_insertion_point(field_get:ns3.SfnSfProto.m_subframeNum)
  return _internal_m_subframenum();
}
inline void SfnSfProto::_internal_set_m_subframenum(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_subframenum_ = value;
}
inline void SfnSfProto::set_m_subframenum(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_subframenum(value);
  // @@protoc_insertion_point(field_set:ns3.SfnSfProto.m_subframeNum)
}

// uint32 m_slotNum = 3;
inline void SfnSfProto::clear_m_slotnum() {
  m_slotnum_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SfnSfProto::_internal_m_slotnum() const {
  return m_slotnum_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SfnSfProto::m_slotnum() const {
  // @@protoc_insertion_point(field_get:ns3.SfnSfProto.m_slotNum)
  return _internal_m_slotnum();
}
inline void SfnSfProto::_internal_set_m_slotnum(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_slotnum_ = value;
}
inline void SfnSfProto::set_m_slotnum(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_slotnum(value);
  // @@protoc_insertion_point(field_set:ns3.SfnSfProto.m_slotNum)
}

// int32 m_numerology = 4;
inline void SfnSfProto::clear_m_numerology() {
  m_numerology_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SfnSfProto::_internal_m_numerology() const {
  return m_numerology_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 SfnSfProto::m_numerology() const {
  // @@protoc_insertion_point(field_get:ns3.SfnSfProto.m_numerology)
  return _internal_m_numerology();
}
inline void SfnSfProto::_internal_set_m_numerology(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  m_numerology_ = value;
}
inline void SfnSfProto::set_m_numerology(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_m_numerology(value);
  // @@protoc_insertion_point(field_set:ns3.SfnSfProto.m_numerology)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace ns3

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_proto_2fsl_2dsfnsf_2eproto
