# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl-mac-pdu-tag.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import sl_sfnsf_pb2 as sl__sfnsf__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='sl-mac-pdu-tag.proto',
  package='ns3',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x14sl-mac-pdu-tag.proto\x12\x03ns3\x1a\x0esl-sfnsf.proto\"\x91\x01\n\x12NrSlMacPduTagProto\x12\x0e\n\x06m_rnti\x18\x01 \x01(\r\x12\x12\n\nm_symStart\x18\x02 \x01(\r\x12\x10\n\x08m_numSym\x18\x03 \x01(\r\x12\x10\n\x08m_tbSize\x18\x04 \x01(\r\x12\x11\n\tm_dstL2Id\x18\x05 \x01(\r\x12 \n\x07m_sfnSf\x18\x06 \x01(\x0b\x32\x0f.ns3.SfnSfProtob\x06proto3')
  ,
  dependencies=[sl__sfnsf__pb2.DESCRIPTOR,])




_NRSLMACPDUTAGPROTO = _descriptor.Descriptor(
  name='NrSlMacPduTagProto',
  full_name='ns3.NrSlMacPduTagProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_rnti', full_name='ns3.NrSlMacPduTagProto.m_rnti', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_symStart', full_name='ns3.NrSlMacPduTagProto.m_symStart', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_numSym', full_name='ns3.NrSlMacPduTagProto.m_numSym', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_tbSize', full_name='ns3.NrSlMacPduTagProto.m_tbSize', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_dstL2Id', full_name='ns3.NrSlMacPduTagProto.m_dstL2Id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='m_sfnSf', full_name='ns3.NrSlMacPduTagProto.m_sfnSf', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=191,
)

_NRSLMACPDUTAGPROTO.fields_by_name['m_sfnSf'].message_type = sl__sfnsf__pb2._SFNSFPROTO
DESCRIPTOR.message_types_by_name['NrSlMacPduTagProto'] = _NRSLMACPDUTAGPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NrSlMacPduTagProto = _reflection.GeneratedProtocolMessageType('NrSlMacPduTagProto', (_message.Message,), dict(
  DESCRIPTOR = _NRSLMACPDUTAGPROTO,
  __module__ = 'sl_mac_pdu_tag_pb2'
  # @@protoc_insertion_point(class_scope:ns3.NrSlMacPduTagProto)
  ))
_sym_db.RegisterMessage(NrSlMacPduTagProto)


# @@protoc_insertion_point(module_scope)
