# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sl-sci-msg.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sl-sci-msg.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\003ns3',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10sl-sci-msg.proto\"\x82\x02\n\x12NrSlMacPduTagProto\x12\x0e\n\x06m_rnti\x18\x01 \x01(\r\x12\x12\n\nm_symStart\x18\x02 \x01(\r\x12\x10\n\x08m_numSym\x18\x03 \x01(\r\x12\x10\n\x08m_tbSize\x18\x04 \x01(\r\x12\x11\n\tm_dstL2Id\x18\x05 \x01(\r\x12/\n\x07m_sfnSf\x18\x06 \x01(\x0b\x32\x1e.NrSlMacPduTagProto.SfnSfProto\x1a`\n\nSfnSfProto\x12\x12\n\nm_frameNum\x18\x01 \x01(\r\x12\x15\n\rm_subframeNum\x18\x02 \x01(\r\x12\x11\n\tm_slotNum\x18\x03 \x01(\r\x12\x14\n\x0cm_numerology\x18\x04 \x01(\r\"\xd8\x03\n\x15NrSlSciF1aHeaderProto\x12\x1a\n\x12m_totalSubChannels\x18\x01 \x01(\r\x12\x12\n\nm_priority\x18\x02 \x01(\r\x12\x1e\n\x16m_indexStartSubChannel\x18\x03 \x01(\r\x12\x1a\n\x12m_lengthSubChannel\x18\x04 \x01(\r\x12\r\n\x05m_mcs\x18\x05 \x01(\r\x12!\n\x19m_slResourceReservePeriod\x18\x06 \x01(\r\x12\x1c\n\x14m_slMaxNumPerReserve\x18\x07 \x01(\r\x12\x1b\n\x13m_slSciStage2Format\x18\x08 \x01(\r\x12\x1d\n\x15m_indexStartSbChReTx1\x18\t \x01(\r\x12\x1d\n\x15m_indexStartSbChReTx2\x18\n \x01(\r\x12\x12\n\nm_gapReTx1\x18\x0b \x01(\r\x12\x12\n\nm_gapReTx2\x18\x0c \x01(\r\x12\x44\n\tsciFormat\x18\r \x03(\x0e\x32-.NrSlSciF1aHeaderProto.SciStage2Format_tProtoB\x02\x10\x01\":\n\x16SciStage2Format_tProto\x12\x0f\n\x0bSciFormat2A\x10\x00\x12\x0f\n\x0bSciFormat2B\x10\x01\x42\x06\xaa\x02\x03ns3b\x06proto3'
)



_NRSLSCIF1AHEADERPROTO_SCISTAGE2FORMAT_TPROTO = _descriptor.EnumDescriptor(
  name='SciStage2Format_tProto',
  full_name='NrSlSciF1aHeaderProto.SciStage2Format_tProto',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SciFormat2A', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SciFormat2B', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=696,
  serialized_end=754,
)
_sym_db.RegisterEnumDescriptor(_NRSLSCIF1AHEADERPROTO_SCISTAGE2FORMAT_TPROTO)


_NRSLMACPDUTAGPROTO_SFNSFPROTO = _descriptor.Descriptor(
  name='SfnSfProto',
  full_name='NrSlMacPduTagProto.SfnSfProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_frameNum', full_name='NrSlMacPduTagProto.SfnSfProto.m_frameNum', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_subframeNum', full_name='NrSlMacPduTagProto.SfnSfProto.m_subframeNum', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_slotNum', full_name='NrSlMacPduTagProto.SfnSfProto.m_slotNum', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_numerology', full_name='NrSlMacPduTagProto.SfnSfProto.m_numerology', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=279,
)

_NRSLMACPDUTAGPROTO = _descriptor.Descriptor(
  name='NrSlMacPduTagProto',
  full_name='NrSlMacPduTagProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_rnti', full_name='NrSlMacPduTagProto.m_rnti', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_symStart', full_name='NrSlMacPduTagProto.m_symStart', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_numSym', full_name='NrSlMacPduTagProto.m_numSym', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_tbSize', full_name='NrSlMacPduTagProto.m_tbSize', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_dstL2Id', full_name='NrSlMacPduTagProto.m_dstL2Id', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_sfnSf', full_name='NrSlMacPduTagProto.m_sfnSf', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_NRSLMACPDUTAGPROTO_SFNSFPROTO, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=279,
)


_NRSLSCIF1AHEADERPROTO = _descriptor.Descriptor(
  name='NrSlSciF1aHeaderProto',
  full_name='NrSlSciF1aHeaderProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='m_totalSubChannels', full_name='NrSlSciF1aHeaderProto.m_totalSubChannels', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_priority', full_name='NrSlSciF1aHeaderProto.m_priority', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_indexStartSubChannel', full_name='NrSlSciF1aHeaderProto.m_indexStartSubChannel', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_lengthSubChannel', full_name='NrSlSciF1aHeaderProto.m_lengthSubChannel', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_mcs', full_name='NrSlSciF1aHeaderProto.m_mcs', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_slResourceReservePeriod', full_name='NrSlSciF1aHeaderProto.m_slResourceReservePeriod', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_slMaxNumPerReserve', full_name='NrSlSciF1aHeaderProto.m_slMaxNumPerReserve', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_slSciStage2Format', full_name='NrSlSciF1aHeaderProto.m_slSciStage2Format', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_indexStartSbChReTx1', full_name='NrSlSciF1aHeaderProto.m_indexStartSbChReTx1', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_indexStartSbChReTx2', full_name='NrSlSciF1aHeaderProto.m_indexStartSbChReTx2', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_gapReTx1', full_name='NrSlSciF1aHeaderProto.m_gapReTx1', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='m_gapReTx2', full_name='NrSlSciF1aHeaderProto.m_gapReTx2', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sciFormat', full_name='NrSlSciF1aHeaderProto.sciFormat', index=12,
      number=13, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=b'\020\001', file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _NRSLSCIF1AHEADERPROTO_SCISTAGE2FORMAT_TPROTO,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=754,
)

_NRSLMACPDUTAGPROTO_SFNSFPROTO.containing_type = _NRSLMACPDUTAGPROTO
_NRSLMACPDUTAGPROTO.fields_by_name['m_sfnSf'].message_type = _NRSLMACPDUTAGPROTO_SFNSFPROTO
_NRSLSCIF1AHEADERPROTO.fields_by_name['sciFormat'].enum_type = _NRSLSCIF1AHEADERPROTO_SCISTAGE2FORMAT_TPROTO
_NRSLSCIF1AHEADERPROTO_SCISTAGE2FORMAT_TPROTO.containing_type = _NRSLSCIF1AHEADERPROTO
DESCRIPTOR.message_types_by_name['NrSlMacPduTagProto'] = _NRSLMACPDUTAGPROTO
DESCRIPTOR.message_types_by_name['NrSlSciF1aHeaderProto'] = _NRSLSCIF1AHEADERPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NrSlMacPduTagProto = _reflection.GeneratedProtocolMessageType('NrSlMacPduTagProto', (_message.Message,), {

  'SfnSfProto' : _reflection.GeneratedProtocolMessageType('SfnSfProto', (_message.Message,), {
    'DESCRIPTOR' : _NRSLMACPDUTAGPROTO_SFNSFPROTO,
    '__module__' : 'sl_sci_msg_pb2'
    # @@protoc_insertion_point(class_scope:NrSlMacPduTagProto.SfnSfProto)
    })
  ,
  'DESCRIPTOR' : _NRSLMACPDUTAGPROTO,
  '__module__' : 'sl_sci_msg_pb2'
  # @@protoc_insertion_point(class_scope:NrSlMacPduTagProto)
  })
_sym_db.RegisterMessage(NrSlMacPduTagProto)
_sym_db.RegisterMessage(NrSlMacPduTagProto.SfnSfProto)

NrSlSciF1aHeaderProto = _reflection.GeneratedProtocolMessageType('NrSlSciF1aHeaderProto', (_message.Message,), {
  'DESCRIPTOR' : _NRSLSCIF1AHEADERPROTO,
  '__module__' : 'sl_sci_msg_pb2'
  # @@protoc_insertion_point(class_scope:NrSlSciF1aHeaderProto)
  })
_sym_db.RegisterMessage(NrSlSciF1aHeaderProto)


DESCRIPTOR._options = None
_NRSLSCIF1AHEADERPROTO.fields_by_name['sciFormat']._options = None
# @@protoc_insertion_point(module_scope)
