// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sl-mac-pdu-tag.proto

#ifndef PROTOBUF_INCLUDED_sl_2dmac_2dpdu_2dtag_2eproto
#define PROTOBUF_INCLUDED_sl_2dmac_2dpdu_2dtag_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "sl-sfnsf.pb.h"
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_sl_2dmac_2dpdu_2dtag_2eproto 

namespace protobuf_sl_2dmac_2dpdu_2dtag_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_sl_2dmac_2dpdu_2dtag_2eproto
namespace ns3 {
class NrSlMacPduTagProto;
class NrSlMacPduTagProtoDefaultTypeInternal;
extern NrSlMacPduTagProtoDefaultTypeInternal _NrSlMacPduTagProto_default_instance_;
}  // namespace ns3
namespace google {
namespace protobuf {
template<> ::ns3::NrSlMacPduTagProto* Arena::CreateMaybeMessage<::ns3::NrSlMacPduTagProto>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace ns3 {

// ===================================================================

class NrSlMacPduTagProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ns3.NrSlMacPduTagProto) */ {
 public:
  NrSlMacPduTagProto();
  virtual ~NrSlMacPduTagProto();

  NrSlMacPduTagProto(const NrSlMacPduTagProto& from);

  inline NrSlMacPduTagProto& operator=(const NrSlMacPduTagProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NrSlMacPduTagProto(NrSlMacPduTagProto&& from) noexcept
    : NrSlMacPduTagProto() {
    *this = ::std::move(from);
  }

  inline NrSlMacPduTagProto& operator=(NrSlMacPduTagProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NrSlMacPduTagProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NrSlMacPduTagProto* internal_default_instance() {
    return reinterpret_cast<const NrSlMacPduTagProto*>(
               &_NrSlMacPduTagProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(NrSlMacPduTagProto* other);
  friend void swap(NrSlMacPduTagProto& a, NrSlMacPduTagProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NrSlMacPduTagProto* New() const final {
    return CreateMaybeMessage<NrSlMacPduTagProto>(NULL);
  }

  NrSlMacPduTagProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NrSlMacPduTagProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const NrSlMacPduTagProto& from);
  void MergeFrom(const NrSlMacPduTagProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NrSlMacPduTagProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .ns3.SfnSfProto m_sfnSf = 6;
  bool has_m_sfnsf() const;
  void clear_m_sfnsf();
  static const int kMSfnSfFieldNumber = 6;
  private:
  const ::ns3::SfnSfProto& _internal_m_sfnsf() const;
  public:
  const ::ns3::SfnSfProto& m_sfnsf() const;
  ::ns3::SfnSfProto* release_m_sfnsf();
  ::ns3::SfnSfProto* mutable_m_sfnsf();
  void set_allocated_m_sfnsf(::ns3::SfnSfProto* m_sfnsf);

  // uint32 m_rnti = 1;
  void clear_m_rnti();
  static const int kMRntiFieldNumber = 1;
  ::google::protobuf::uint32 m_rnti() const;
  void set_m_rnti(::google::protobuf::uint32 value);

  // uint32 m_symStart = 2;
  void clear_m_symstart();
  static const int kMSymStartFieldNumber = 2;
  ::google::protobuf::uint32 m_symstart() const;
  void set_m_symstart(::google::protobuf::uint32 value);

  // uint32 m_numSym = 3;
  void clear_m_numsym();
  static const int kMNumSymFieldNumber = 3;
  ::google::protobuf::uint32 m_numsym() const;
  void set_m_numsym(::google::protobuf::uint32 value);

  // uint32 m_tbSize = 4;
  void clear_m_tbsize();
  static const int kMTbSizeFieldNumber = 4;
  ::google::protobuf::uint32 m_tbsize() const;
  void set_m_tbsize(::google::protobuf::uint32 value);

  // uint32 m_dstL2Id = 5;
  void clear_m_dstl2id();
  static const int kMDstL2IdFieldNumber = 5;
  ::google::protobuf::uint32 m_dstl2id() const;
  void set_m_dstl2id(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ns3.NrSlMacPduTagProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::ns3::SfnSfProto* m_sfnsf_;
  ::google::protobuf::uint32 m_rnti_;
  ::google::protobuf::uint32 m_symstart_;
  ::google::protobuf::uint32 m_numsym_;
  ::google::protobuf::uint32 m_tbsize_;
  ::google::protobuf::uint32 m_dstl2id_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_sl_2dmac_2dpdu_2dtag_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NrSlMacPduTagProto

// uint32 m_rnti = 1;
inline void NrSlMacPduTagProto::clear_m_rnti() {
  m_rnti_ = 0u;
}
inline ::google::protobuf::uint32 NrSlMacPduTagProto::m_rnti() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlMacPduTagProto.m_rnti)
  return m_rnti_;
}
inline void NrSlMacPduTagProto::set_m_rnti(::google::protobuf::uint32 value) {
  
  m_rnti_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlMacPduTagProto.m_rnti)
}

// uint32 m_symStart = 2;
inline void NrSlMacPduTagProto::clear_m_symstart() {
  m_symstart_ = 0u;
}
inline ::google::protobuf::uint32 NrSlMacPduTagProto::m_symstart() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlMacPduTagProto.m_symStart)
  return m_symstart_;
}
inline void NrSlMacPduTagProto::set_m_symstart(::google::protobuf::uint32 value) {
  
  m_symstart_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlMacPduTagProto.m_symStart)
}

// uint32 m_numSym = 3;
inline void NrSlMacPduTagProto::clear_m_numsym() {
  m_numsym_ = 0u;
}
inline ::google::protobuf::uint32 NrSlMacPduTagProto::m_numsym() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlMacPduTagProto.m_numSym)
  return m_numsym_;
}
inline void NrSlMacPduTagProto::set_m_numsym(::google::protobuf::uint32 value) {
  
  m_numsym_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlMacPduTagProto.m_numSym)
}

// uint32 m_tbSize = 4;
inline void NrSlMacPduTagProto::clear_m_tbsize() {
  m_tbsize_ = 0u;
}
inline ::google::protobuf::uint32 NrSlMacPduTagProto::m_tbsize() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlMacPduTagProto.m_tbSize)
  return m_tbsize_;
}
inline void NrSlMacPduTagProto::set_m_tbsize(::google::protobuf::uint32 value) {
  
  m_tbsize_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlMacPduTagProto.m_tbSize)
}

// uint32 m_dstL2Id = 5;
inline void NrSlMacPduTagProto::clear_m_dstl2id() {
  m_dstl2id_ = 0u;
}
inline ::google::protobuf::uint32 NrSlMacPduTagProto::m_dstl2id() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlMacPduTagProto.m_dstL2Id)
  return m_dstl2id_;
}
inline void NrSlMacPduTagProto::set_m_dstl2id(::google::protobuf::uint32 value) {
  
  m_dstl2id_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlMacPduTagProto.m_dstL2Id)
}

// .ns3.SfnSfProto m_sfnSf = 6;
inline bool NrSlMacPduTagProto::has_m_sfnsf() const {
  return this != internal_default_instance() && m_sfnsf_ != NULL;
}
inline const ::ns3::SfnSfProto& NrSlMacPduTagProto::_internal_m_sfnsf() const {
  return *m_sfnsf_;
}
inline const ::ns3::SfnSfProto& NrSlMacPduTagProto::m_sfnsf() const {
  const ::ns3::SfnSfProto* p = m_sfnsf_;
  // @@protoc_insertion_point(field_get:ns3.NrSlMacPduTagProto.m_sfnSf)
  return p != NULL ? *p : *reinterpret_cast<const ::ns3::SfnSfProto*>(
      &::ns3::_SfnSfProto_default_instance_);
}
inline ::ns3::SfnSfProto* NrSlMacPduTagProto::release_m_sfnsf() {
  // @@protoc_insertion_point(field_release:ns3.NrSlMacPduTagProto.m_sfnSf)
  
  ::ns3::SfnSfProto* temp = m_sfnsf_;
  m_sfnsf_ = NULL;
  return temp;
}
inline ::ns3::SfnSfProto* NrSlMacPduTagProto::mutable_m_sfnsf() {
  
  if (m_sfnsf_ == NULL) {
    auto* p = CreateMaybeMessage<::ns3::SfnSfProto>(GetArenaNoVirtual());
    m_sfnsf_ = p;
  }
  // @@protoc_insertion_point(field_mutable:ns3.NrSlMacPduTagProto.m_sfnSf)
  return m_sfnsf_;
}
inline void NrSlMacPduTagProto::set_allocated_m_sfnsf(::ns3::SfnSfProto* m_sfnsf) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(m_sfnsf_);
  }
  if (m_sfnsf) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      m_sfnsf = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, m_sfnsf, submessage_arena);
    }
    
  } else {
    
  }
  m_sfnsf_ = m_sfnsf;
  // @@protoc_insertion_point(field_set_allocated:ns3.NrSlMacPduTagProto.m_sfnSf)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace ns3

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_sl_2dmac_2dpdu_2dtag_2eproto
