// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sl-sci-f1a-header.proto

#ifndef PROTOBUF_INCLUDED_sl_2dsci_2df1a_2dheader_2eproto
#define PROTOBUF_INCLUDED_sl_2dsci_2df1a_2dheader_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_sl_2dsci_2df1a_2dheader_2eproto 

namespace protobuf_sl_2dsci_2df1a_2dheader_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_sl_2dsci_2df1a_2dheader_2eproto
namespace ns3 {
class NrSlSciF1aHeaderProto;
class NrSlSciF1aHeaderProtoDefaultTypeInternal;
extern NrSlSciF1aHeaderProtoDefaultTypeInternal _NrSlSciF1aHeaderProto_default_instance_;
}  // namespace ns3
namespace google {
namespace protobuf {
template<> ::ns3::NrSlSciF1aHeaderProto* Arena::CreateMaybeMessage<::ns3::NrSlSciF1aHeaderProto>(Arena*);
}  // namespace protobuf
}  // namespace google
namespace ns3 {

enum NrSlSciF1aHeaderProto_SciStage2Format_tProto {
  NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciFormat2A = 0,
  NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciFormat2B = 1,
  NrSlSciF1aHeaderProto_SciStage2Format_tProto_NrSlSciF1aHeaderProto_SciStage2Format_tProto_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  NrSlSciF1aHeaderProto_SciStage2Format_tProto_NrSlSciF1aHeaderProto_SciStage2Format_tProto_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool NrSlSciF1aHeaderProto_SciStage2Format_tProto_IsValid(int value);
const NrSlSciF1aHeaderProto_SciStage2Format_tProto NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciStage2Format_tProto_MIN = NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciFormat2A;
const NrSlSciF1aHeaderProto_SciStage2Format_tProto NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciStage2Format_tProto_MAX = NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciFormat2B;
const int NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciStage2Format_tProto_ARRAYSIZE = NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciStage2Format_tProto_MAX + 1;

const ::google::protobuf::EnumDescriptor* NrSlSciF1aHeaderProto_SciStage2Format_tProto_descriptor();
inline const ::std::string& NrSlSciF1aHeaderProto_SciStage2Format_tProto_Name(NrSlSciF1aHeaderProto_SciStage2Format_tProto value) {
  return ::google::protobuf::internal::NameOfEnum(
    NrSlSciF1aHeaderProto_SciStage2Format_tProto_descriptor(), value);
}
inline bool NrSlSciF1aHeaderProto_SciStage2Format_tProto_Parse(
    const ::std::string& name, NrSlSciF1aHeaderProto_SciStage2Format_tProto* value) {
  return ::google::protobuf::internal::ParseNamedEnum<NrSlSciF1aHeaderProto_SciStage2Format_tProto>(
    NrSlSciF1aHeaderProto_SciStage2Format_tProto_descriptor(), name, value);
}
// ===================================================================

class NrSlSciF1aHeaderProto : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:ns3.NrSlSciF1aHeaderProto) */ {
 public:
  NrSlSciF1aHeaderProto();
  virtual ~NrSlSciF1aHeaderProto();

  NrSlSciF1aHeaderProto(const NrSlSciF1aHeaderProto& from);

  inline NrSlSciF1aHeaderProto& operator=(const NrSlSciF1aHeaderProto& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  NrSlSciF1aHeaderProto(NrSlSciF1aHeaderProto&& from) noexcept
    : NrSlSciF1aHeaderProto() {
    *this = ::std::move(from);
  }

  inline NrSlSciF1aHeaderProto& operator=(NrSlSciF1aHeaderProto&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const NrSlSciF1aHeaderProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NrSlSciF1aHeaderProto* internal_default_instance() {
    return reinterpret_cast<const NrSlSciF1aHeaderProto*>(
               &_NrSlSciF1aHeaderProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(NrSlSciF1aHeaderProto* other);
  friend void swap(NrSlSciF1aHeaderProto& a, NrSlSciF1aHeaderProto& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline NrSlSciF1aHeaderProto* New() const final {
    return CreateMaybeMessage<NrSlSciF1aHeaderProto>(NULL);
  }

  NrSlSciF1aHeaderProto* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<NrSlSciF1aHeaderProto>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const NrSlSciF1aHeaderProto& from);
  void MergeFrom(const NrSlSciF1aHeaderProto& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NrSlSciF1aHeaderProto* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef NrSlSciF1aHeaderProto_SciStage2Format_tProto SciStage2Format_tProto;
  static const SciStage2Format_tProto SciFormat2A =
    NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciFormat2A;
  static const SciStage2Format_tProto SciFormat2B =
    NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciFormat2B;
  static inline bool SciStage2Format_tProto_IsValid(int value) {
    return NrSlSciF1aHeaderProto_SciStage2Format_tProto_IsValid(value);
  }
  static const SciStage2Format_tProto SciStage2Format_tProto_MIN =
    NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciStage2Format_tProto_MIN;
  static const SciStage2Format_tProto SciStage2Format_tProto_MAX =
    NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciStage2Format_tProto_MAX;
  static const int SciStage2Format_tProto_ARRAYSIZE =
    NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciStage2Format_tProto_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  SciStage2Format_tProto_descriptor() {
    return NrSlSciF1aHeaderProto_SciStage2Format_tProto_descriptor();
  }
  static inline const ::std::string& SciStage2Format_tProto_Name(SciStage2Format_tProto value) {
    return NrSlSciF1aHeaderProto_SciStage2Format_tProto_Name(value);
  }
  static inline bool SciStage2Format_tProto_Parse(const ::std::string& name,
      SciStage2Format_tProto* value) {
    return NrSlSciF1aHeaderProto_SciStage2Format_tProto_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .ns3.NrSlSciF1aHeaderProto.SciStage2Format_tProto sciFormat = 13 [packed = true];
  int sciformat_size() const;
  void clear_sciformat();
  static const int kSciFormatFieldNumber = 13;
  ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto sciformat(int index) const;
  void set_sciformat(int index, ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto value);
  void add_sciformat(::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto value);
  const ::google::protobuf::RepeatedField<int>& sciformat() const;
  ::google::protobuf::RepeatedField<int>* mutable_sciformat();

  // uint32 m_totalSubChannels = 1;
  void clear_m_totalsubchannels();
  static const int kMTotalSubChannelsFieldNumber = 1;
  ::google::protobuf::uint32 m_totalsubchannels() const;
  void set_m_totalsubchannels(::google::protobuf::uint32 value);

  // uint32 m_priority = 2;
  void clear_m_priority();
  static const int kMPriorityFieldNumber = 2;
  ::google::protobuf::uint32 m_priority() const;
  void set_m_priority(::google::protobuf::uint32 value);

  // uint32 m_indexStartSubChannel = 3;
  void clear_m_indexstartsubchannel();
  static const int kMIndexStartSubChannelFieldNumber = 3;
  ::google::protobuf::uint32 m_indexstartsubchannel() const;
  void set_m_indexstartsubchannel(::google::protobuf::uint32 value);

  // uint32 m_lengthSubChannel = 4;
  void clear_m_lengthsubchannel();
  static const int kMLengthSubChannelFieldNumber = 4;
  ::google::protobuf::uint32 m_lengthsubchannel() const;
  void set_m_lengthsubchannel(::google::protobuf::uint32 value);

  // uint32 m_mcs = 5;
  void clear_m_mcs();
  static const int kMMcsFieldNumber = 5;
  ::google::protobuf::uint32 m_mcs() const;
  void set_m_mcs(::google::protobuf::uint32 value);

  // uint32 m_slResourceReservePeriod = 6;
  void clear_m_slresourcereserveperiod();
  static const int kMSlResourceReservePeriodFieldNumber = 6;
  ::google::protobuf::uint32 m_slresourcereserveperiod() const;
  void set_m_slresourcereserveperiod(::google::protobuf::uint32 value);

  // uint32 m_slMaxNumPerReserve = 7;
  void clear_m_slmaxnumperreserve();
  static const int kMSlMaxNumPerReserveFieldNumber = 7;
  ::google::protobuf::uint32 m_slmaxnumperreserve() const;
  void set_m_slmaxnumperreserve(::google::protobuf::uint32 value);

  // uint32 m_slSciStage2Format = 8;
  void clear_m_slscistage2format();
  static const int kMSlSciStage2FormatFieldNumber = 8;
  ::google::protobuf::uint32 m_slscistage2format() const;
  void set_m_slscistage2format(::google::protobuf::uint32 value);

  // uint32 m_indexStartSbChReTx1 = 9;
  void clear_m_indexstartsbchretx1();
  static const int kMIndexStartSbChReTx1FieldNumber = 9;
  ::google::protobuf::uint32 m_indexstartsbchretx1() const;
  void set_m_indexstartsbchretx1(::google::protobuf::uint32 value);

  // uint32 m_indexStartSbChReTx2 = 10;
  void clear_m_indexstartsbchretx2();
  static const int kMIndexStartSbChReTx2FieldNumber = 10;
  ::google::protobuf::uint32 m_indexstartsbchretx2() const;
  void set_m_indexstartsbchretx2(::google::protobuf::uint32 value);

  // uint32 m_gapReTx1 = 11;
  void clear_m_gapretx1();
  static const int kMGapReTx1FieldNumber = 11;
  ::google::protobuf::uint32 m_gapretx1() const;
  void set_m_gapretx1(::google::protobuf::uint32 value);

  // uint32 m_gapReTx2 = 12;
  void clear_m_gapretx2();
  static const int kMGapReTx2FieldNumber = 12;
  ::google::protobuf::uint32 m_gapretx2() const;
  void set_m_gapretx2(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:ns3.NrSlSciF1aHeaderProto)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedField<int> sciformat_;
  mutable int _sciformat_cached_byte_size_;
  ::google::protobuf::uint32 m_totalsubchannels_;
  ::google::protobuf::uint32 m_priority_;
  ::google::protobuf::uint32 m_indexstartsubchannel_;
  ::google::protobuf::uint32 m_lengthsubchannel_;
  ::google::protobuf::uint32 m_mcs_;
  ::google::protobuf::uint32 m_slresourcereserveperiod_;
  ::google::protobuf::uint32 m_slmaxnumperreserve_;
  ::google::protobuf::uint32 m_slscistage2format_;
  ::google::protobuf::uint32 m_indexstartsbchretx1_;
  ::google::protobuf::uint32 m_indexstartsbchretx2_;
  ::google::protobuf::uint32 m_gapretx1_;
  ::google::protobuf::uint32 m_gapretx2_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  friend struct ::protobuf_sl_2dsci_2df1a_2dheader_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NrSlSciF1aHeaderProto

// uint32 m_totalSubChannels = 1;
inline void NrSlSciF1aHeaderProto::clear_m_totalsubchannels() {
  m_totalsubchannels_ = 0u;
}
inline ::google::protobuf::uint32 NrSlSciF1aHeaderProto::m_totalsubchannels() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_totalSubChannels)
  return m_totalsubchannels_;
}
inline void NrSlSciF1aHeaderProto::set_m_totalsubchannels(::google::protobuf::uint32 value) {
  
  m_totalsubchannels_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_totalSubChannels)
}

// uint32 m_priority = 2;
inline void NrSlSciF1aHeaderProto::clear_m_priority() {
  m_priority_ = 0u;
}
inline ::google::protobuf::uint32 NrSlSciF1aHeaderProto::m_priority() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_priority)
  return m_priority_;
}
inline void NrSlSciF1aHeaderProto::set_m_priority(::google::protobuf::uint32 value) {
  
  m_priority_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_priority)
}

// uint32 m_indexStartSubChannel = 3;
inline void NrSlSciF1aHeaderProto::clear_m_indexstartsubchannel() {
  m_indexstartsubchannel_ = 0u;
}
inline ::google::protobuf::uint32 NrSlSciF1aHeaderProto::m_indexstartsubchannel() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_indexStartSubChannel)
  return m_indexstartsubchannel_;
}
inline void NrSlSciF1aHeaderProto::set_m_indexstartsubchannel(::google::protobuf::uint32 value) {
  
  m_indexstartsubchannel_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_indexStartSubChannel)
}

// uint32 m_lengthSubChannel = 4;
inline void NrSlSciF1aHeaderProto::clear_m_lengthsubchannel() {
  m_lengthsubchannel_ = 0u;
}
inline ::google::protobuf::uint32 NrSlSciF1aHeaderProto::m_lengthsubchannel() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_lengthSubChannel)
  return m_lengthsubchannel_;
}
inline void NrSlSciF1aHeaderProto::set_m_lengthsubchannel(::google::protobuf::uint32 value) {
  
  m_lengthsubchannel_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_lengthSubChannel)
}

// uint32 m_mcs = 5;
inline void NrSlSciF1aHeaderProto::clear_m_mcs() {
  m_mcs_ = 0u;
}
inline ::google::protobuf::uint32 NrSlSciF1aHeaderProto::m_mcs() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_mcs)
  return m_mcs_;
}
inline void NrSlSciF1aHeaderProto::set_m_mcs(::google::protobuf::uint32 value) {
  
  m_mcs_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_mcs)
}

// uint32 m_slResourceReservePeriod = 6;
inline void NrSlSciF1aHeaderProto::clear_m_slresourcereserveperiod() {
  m_slresourcereserveperiod_ = 0u;
}
inline ::google::protobuf::uint32 NrSlSciF1aHeaderProto::m_slresourcereserveperiod() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_slResourceReservePeriod)
  return m_slresourcereserveperiod_;
}
inline void NrSlSciF1aHeaderProto::set_m_slresourcereserveperiod(::google::protobuf::uint32 value) {
  
  m_slresourcereserveperiod_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_slResourceReservePeriod)
}

// uint32 m_slMaxNumPerReserve = 7;
inline void NrSlSciF1aHeaderProto::clear_m_slmaxnumperreserve() {
  m_slmaxnumperreserve_ = 0u;
}
inline ::google::protobuf::uint32 NrSlSciF1aHeaderProto::m_slmaxnumperreserve() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_slMaxNumPerReserve)
  return m_slmaxnumperreserve_;
}
inline void NrSlSciF1aHeaderProto::set_m_slmaxnumperreserve(::google::protobuf::uint32 value) {
  
  m_slmaxnumperreserve_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_slMaxNumPerReserve)
}

// uint32 m_slSciStage2Format = 8;
inline void NrSlSciF1aHeaderProto::clear_m_slscistage2format() {
  m_slscistage2format_ = 0u;
}
inline ::google::protobuf::uint32 NrSlSciF1aHeaderProto::m_slscistage2format() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_slSciStage2Format)
  return m_slscistage2format_;
}
inline void NrSlSciF1aHeaderProto::set_m_slscistage2format(::google::protobuf::uint32 value) {
  
  m_slscistage2format_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_slSciStage2Format)
}

// uint32 m_indexStartSbChReTx1 = 9;
inline void NrSlSciF1aHeaderProto::clear_m_indexstartsbchretx1() {
  m_indexstartsbchretx1_ = 0u;
}
inline ::google::protobuf::uint32 NrSlSciF1aHeaderProto::m_indexstartsbchretx1() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_indexStartSbChReTx1)
  return m_indexstartsbchretx1_;
}
inline void NrSlSciF1aHeaderProto::set_m_indexstartsbchretx1(::google::protobuf::uint32 value) {
  
  m_indexstartsbchretx1_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_indexStartSbChReTx1)
}

// uint32 m_indexStartSbChReTx2 = 10;
inline void NrSlSciF1aHeaderProto::clear_m_indexstartsbchretx2() {
  m_indexstartsbchretx2_ = 0u;
}
inline ::google::protobuf::uint32 NrSlSciF1aHeaderProto::m_indexstartsbchretx2() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_indexStartSbChReTx2)
  return m_indexstartsbchretx2_;
}
inline void NrSlSciF1aHeaderProto::set_m_indexstartsbchretx2(::google::protobuf::uint32 value) {
  
  m_indexstartsbchretx2_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_indexStartSbChReTx2)
}

// uint32 m_gapReTx1 = 11;
inline void NrSlSciF1aHeaderProto::clear_m_gapretx1() {
  m_gapretx1_ = 0u;
}
inline ::google::protobuf::uint32 NrSlSciF1aHeaderProto::m_gapretx1() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_gapReTx1)
  return m_gapretx1_;
}
inline void NrSlSciF1aHeaderProto::set_m_gapretx1(::google::protobuf::uint32 value) {
  
  m_gapretx1_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_gapReTx1)
}

// uint32 m_gapReTx2 = 12;
inline void NrSlSciF1aHeaderProto::clear_m_gapretx2() {
  m_gapretx2_ = 0u;
}
inline ::google::protobuf::uint32 NrSlSciF1aHeaderProto::m_gapretx2() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_gapReTx2)
  return m_gapretx2_;
}
inline void NrSlSciF1aHeaderProto::set_m_gapretx2(::google::protobuf::uint32 value) {
  
  m_gapretx2_ = value;
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_gapReTx2)
}

// repeated .ns3.NrSlSciF1aHeaderProto.SciStage2Format_tProto sciFormat = 13 [packed = true];
inline int NrSlSciF1aHeaderProto::sciformat_size() const {
  return sciformat_.size();
}
inline void NrSlSciF1aHeaderProto::clear_sciformat() {
  sciformat_.Clear();
}
inline ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto NrSlSciF1aHeaderProto::sciformat(int index) const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.sciFormat)
  return static_cast< ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto >(sciformat_.Get(index));
}
inline void NrSlSciF1aHeaderProto::set_sciformat(int index, ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto value) {
  sciformat_.Set(index, value);
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.sciFormat)
}
inline void NrSlSciF1aHeaderProto::add_sciformat(::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto value) {
  sciformat_.Add(value);
  // @@protoc_insertion_point(field_add:ns3.NrSlSciF1aHeaderProto.sciFormat)
}
inline const ::google::protobuf::RepeatedField<int>&
NrSlSciF1aHeaderProto::sciformat() const {
  // @@protoc_insertion_point(field_list:ns3.NrSlSciF1aHeaderProto.sciFormat)
  return sciformat_;
}
inline ::google::protobuf::RepeatedField<int>*
NrSlSciF1aHeaderProto::mutable_sciformat() {
  // @@protoc_insertion_point(field_mutable_list:ns3.NrSlSciF1aHeaderProto.sciFormat)
  return &sciformat_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace ns3

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto>() {
  return ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_sl_2dsci_2df1a_2dheader_2eproto
