// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: sl-sci-msg.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_sl_2dsci_2dmsg_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_sl_2dsci_2dmsg_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_sl_2dsci_2dmsg_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_sl_2dsci_2dmsg_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[3]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_sl_2dsci_2dmsg_2eproto;
namespace ns3 {
class NrSlMacPduTagProto;
class NrSlMacPduTagProtoDefaultTypeInternal;
extern NrSlMacPduTagProtoDefaultTypeInternal _NrSlMacPduTagProto_default_instance_;
class NrSlMacPduTagProto_SfnSfProto;
class NrSlMacPduTagProto_SfnSfProtoDefaultTypeInternal;
extern NrSlMacPduTagProto_SfnSfProtoDefaultTypeInternal _NrSlMacPduTagProto_SfnSfProto_default_instance_;
class NrSlSciF1aHeaderProto;
class NrSlSciF1aHeaderProtoDefaultTypeInternal;
extern NrSlSciF1aHeaderProtoDefaultTypeInternal _NrSlSciF1aHeaderProto_default_instance_;
}  // namespace ns3
PROTOBUF_NAMESPACE_OPEN
template<> ::ns3::NrSlMacPduTagProto* Arena::CreateMaybeMessage<::ns3::NrSlMacPduTagProto>(Arena*);
template<> ::ns3::NrSlMacPduTagProto_SfnSfProto* Arena::CreateMaybeMessage<::ns3::NrSlMacPduTagProto_SfnSfProto>(Arena*);
template<> ::ns3::NrSlSciF1aHeaderProto* Arena::CreateMaybeMessage<::ns3::NrSlSciF1aHeaderProto>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ns3 {

enum NrSlSciF1aHeaderProto_SciStage2Format_tProto : int {
  NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciFormat2A = 0,
  NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciFormat2B = 1,
  NrSlSciF1aHeaderProto_SciStage2Format_tProto_NrSlSciF1aHeaderProto_SciStage2Format_tProto_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  NrSlSciF1aHeaderProto_SciStage2Format_tProto_NrSlSciF1aHeaderProto_SciStage2Format_tProto_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool NrSlSciF1aHeaderProto_SciStage2Format_tProto_IsValid(int value);
constexpr NrSlSciF1aHeaderProto_SciStage2Format_tProto NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciStage2Format_tProto_MIN = NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciFormat2A;
constexpr NrSlSciF1aHeaderProto_SciStage2Format_tProto NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciStage2Format_tProto_MAX = NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciFormat2B;
constexpr int NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciStage2Format_tProto_ARRAYSIZE = NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciStage2Format_tProto_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* NrSlSciF1aHeaderProto_SciStage2Format_tProto_descriptor();
template<typename T>
inline const std::string& NrSlSciF1aHeaderProto_SciStage2Format_tProto_Name(T enum_t_value) {
  static_assert(::std::is_same<T, NrSlSciF1aHeaderProto_SciStage2Format_tProto>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function NrSlSciF1aHeaderProto_SciStage2Format_tProto_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    NrSlSciF1aHeaderProto_SciStage2Format_tProto_descriptor(), enum_t_value);
}
inline bool NrSlSciF1aHeaderProto_SciStage2Format_tProto_Parse(
    const std::string& name, NrSlSciF1aHeaderProto_SciStage2Format_tProto* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<NrSlSciF1aHeaderProto_SciStage2Format_tProto>(
    NrSlSciF1aHeaderProto_SciStage2Format_tProto_descriptor(), name, value);
}
// ===================================================================

class NrSlMacPduTagProto_SfnSfProto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ns3.NrSlMacPduTagProto.SfnSfProto) */ {
 public:
  inline NrSlMacPduTagProto_SfnSfProto() : NrSlMacPduTagProto_SfnSfProto(nullptr) {};
  virtual ~NrSlMacPduTagProto_SfnSfProto();

  NrSlMacPduTagProto_SfnSfProto(const NrSlMacPduTagProto_SfnSfProto& from);
  NrSlMacPduTagProto_SfnSfProto(NrSlMacPduTagProto_SfnSfProto&& from) noexcept
    : NrSlMacPduTagProto_SfnSfProto() {
    *this = ::std::move(from);
  }

  inline NrSlMacPduTagProto_SfnSfProto& operator=(const NrSlMacPduTagProto_SfnSfProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline NrSlMacPduTagProto_SfnSfProto& operator=(NrSlMacPduTagProto_SfnSfProto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NrSlMacPduTagProto_SfnSfProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NrSlMacPduTagProto_SfnSfProto* internal_default_instance() {
    return reinterpret_cast<const NrSlMacPduTagProto_SfnSfProto*>(
               &_NrSlMacPduTagProto_SfnSfProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(NrSlMacPduTagProto_SfnSfProto& a, NrSlMacPduTagProto_SfnSfProto& b) {
    a.Swap(&b);
  }
  inline void Swap(NrSlMacPduTagProto_SfnSfProto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NrSlMacPduTagProto_SfnSfProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NrSlMacPduTagProto_SfnSfProto* New() const final {
    return CreateMaybeMessage<NrSlMacPduTagProto_SfnSfProto>(nullptr);
  }

  NrSlMacPduTagProto_SfnSfProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NrSlMacPduTagProto_SfnSfProto>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NrSlMacPduTagProto_SfnSfProto& from);
  void MergeFrom(const NrSlMacPduTagProto_SfnSfProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NrSlMacPduTagProto_SfnSfProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ns3.NrSlMacPduTagProto.SfnSfProto";
  }
  protected:
  explicit NrSlMacPduTagProto_SfnSfProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sl_2dsci_2dmsg_2eproto);
    return ::descriptor_table_sl_2dsci_2dmsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMFrameNumFieldNumber = 1,
    kMSubframeNumFieldNumber = 2,
    kMSlotNumFieldNumber = 3,
    kMNumerologyFieldNumber = 4,
  };
  // uint32 m_frameNum = 1;
  void clear_m_framenum();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_framenum() const;
  void set_m_framenum(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_framenum() const;
  void _internal_set_m_framenum(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_subframeNum = 2;
  void clear_m_subframenum();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_subframenum() const;
  void set_m_subframenum(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_subframenum() const;
  void _internal_set_m_subframenum(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_slotNum = 3;
  void clear_m_slotnum();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_slotnum() const;
  void set_m_slotnum(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_slotnum() const;
  void _internal_set_m_slotnum(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_numerology = 4;
  void clear_m_numerology();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_numerology() const;
  void set_m_numerology(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_numerology() const;
  void _internal_set_m_numerology(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:ns3.NrSlMacPduTagProto.SfnSfProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_framenum_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_subframenum_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_slotnum_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_numerology_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sl_2dsci_2dmsg_2eproto;
};
// -------------------------------------------------------------------

class NrSlMacPduTagProto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ns3.NrSlMacPduTagProto) */ {
 public:
  inline NrSlMacPduTagProto() : NrSlMacPduTagProto(nullptr) {};
  virtual ~NrSlMacPduTagProto();

  NrSlMacPduTagProto(const NrSlMacPduTagProto& from);
  NrSlMacPduTagProto(NrSlMacPduTagProto&& from) noexcept
    : NrSlMacPduTagProto() {
    *this = ::std::move(from);
  }

  inline NrSlMacPduTagProto& operator=(const NrSlMacPduTagProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline NrSlMacPduTagProto& operator=(NrSlMacPduTagProto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NrSlMacPduTagProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NrSlMacPduTagProto* internal_default_instance() {
    return reinterpret_cast<const NrSlMacPduTagProto*>(
               &_NrSlMacPduTagProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(NrSlMacPduTagProto& a, NrSlMacPduTagProto& b) {
    a.Swap(&b);
  }
  inline void Swap(NrSlMacPduTagProto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NrSlMacPduTagProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NrSlMacPduTagProto* New() const final {
    return CreateMaybeMessage<NrSlMacPduTagProto>(nullptr);
  }

  NrSlMacPduTagProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NrSlMacPduTagProto>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NrSlMacPduTagProto& from);
  void MergeFrom(const NrSlMacPduTagProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NrSlMacPduTagProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ns3.NrSlMacPduTagProto";
  }
  protected:
  explicit NrSlMacPduTagProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sl_2dsci_2dmsg_2eproto);
    return ::descriptor_table_sl_2dsci_2dmsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef NrSlMacPduTagProto_SfnSfProto SfnSfProto;

  // accessors -------------------------------------------------------

  enum : int {
    kMSfnSfFieldNumber = 6,
    kMRntiFieldNumber = 1,
    kMSymStartFieldNumber = 2,
    kMNumSymFieldNumber = 3,
    kMTbSizeFieldNumber = 4,
    kMDstL2IdFieldNumber = 5,
  };
  // .ns3.NrSlMacPduTagProto.SfnSfProto m_sfnSf = 6;
  bool has_m_sfnsf() const;
  private:
  bool _internal_has_m_sfnsf() const;
  public:
  void clear_m_sfnsf();
  const ::ns3::NrSlMacPduTagProto_SfnSfProto& m_sfnsf() const;
  ::ns3::NrSlMacPduTagProto_SfnSfProto* release_m_sfnsf();
  ::ns3::NrSlMacPduTagProto_SfnSfProto* mutable_m_sfnsf();
  void set_allocated_m_sfnsf(::ns3::NrSlMacPduTagProto_SfnSfProto* m_sfnsf);
  private:
  const ::ns3::NrSlMacPduTagProto_SfnSfProto& _internal_m_sfnsf() const;
  ::ns3::NrSlMacPduTagProto_SfnSfProto* _internal_mutable_m_sfnsf();
  public:
  void unsafe_arena_set_allocated_m_sfnsf(
      ::ns3::NrSlMacPduTagProto_SfnSfProto* m_sfnsf);
  ::ns3::NrSlMacPduTagProto_SfnSfProto* unsafe_arena_release_m_sfnsf();

  // uint32 m_rnti = 1;
  void clear_m_rnti();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_rnti() const;
  void set_m_rnti(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_rnti() const;
  void _internal_set_m_rnti(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_symStart = 2;
  void clear_m_symstart();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_symstart() const;
  void set_m_symstart(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_symstart() const;
  void _internal_set_m_symstart(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_numSym = 3;
  void clear_m_numsym();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_numsym() const;
  void set_m_numsym(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_numsym() const;
  void _internal_set_m_numsym(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_tbSize = 4;
  void clear_m_tbsize();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_tbsize() const;
  void set_m_tbsize(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_tbsize() const;
  void _internal_set_m_tbsize(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_dstL2Id = 5;
  void clear_m_dstl2id();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_dstl2id() const;
  void set_m_dstl2id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_dstl2id() const;
  void _internal_set_m_dstl2id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:ns3.NrSlMacPduTagProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::ns3::NrSlMacPduTagProto_SfnSfProto* m_sfnsf_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_rnti_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_symstart_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_numsym_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_tbsize_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_dstl2id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sl_2dsci_2dmsg_2eproto;
};
// -------------------------------------------------------------------

class NrSlSciF1aHeaderProto PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ns3.NrSlSciF1aHeaderProto) */ {
 public:
  inline NrSlSciF1aHeaderProto() : NrSlSciF1aHeaderProto(nullptr) {};
  virtual ~NrSlSciF1aHeaderProto();

  NrSlSciF1aHeaderProto(const NrSlSciF1aHeaderProto& from);
  NrSlSciF1aHeaderProto(NrSlSciF1aHeaderProto&& from) noexcept
    : NrSlSciF1aHeaderProto() {
    *this = ::std::move(from);
  }

  inline NrSlSciF1aHeaderProto& operator=(const NrSlSciF1aHeaderProto& from) {
    CopyFrom(from);
    return *this;
  }
  inline NrSlSciF1aHeaderProto& operator=(NrSlSciF1aHeaderProto&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const NrSlSciF1aHeaderProto& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const NrSlSciF1aHeaderProto* internal_default_instance() {
    return reinterpret_cast<const NrSlSciF1aHeaderProto*>(
               &_NrSlSciF1aHeaderProto_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(NrSlSciF1aHeaderProto& a, NrSlSciF1aHeaderProto& b) {
    a.Swap(&b);
  }
  inline void Swap(NrSlSciF1aHeaderProto* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NrSlSciF1aHeaderProto* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline NrSlSciF1aHeaderProto* New() const final {
    return CreateMaybeMessage<NrSlSciF1aHeaderProto>(nullptr);
  }

  NrSlSciF1aHeaderProto* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<NrSlSciF1aHeaderProto>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const NrSlSciF1aHeaderProto& from);
  void MergeFrom(const NrSlSciF1aHeaderProto& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NrSlSciF1aHeaderProto* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ns3.NrSlSciF1aHeaderProto";
  }
  protected:
  explicit NrSlSciF1aHeaderProto(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_sl_2dsci_2dmsg_2eproto);
    return ::descriptor_table_sl_2dsci_2dmsg_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef NrSlSciF1aHeaderProto_SciStage2Format_tProto SciStage2Format_tProto;
  static constexpr SciStage2Format_tProto SciFormat2A =
    NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciFormat2A;
  static constexpr SciStage2Format_tProto SciFormat2B =
    NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciFormat2B;
  static inline bool SciStage2Format_tProto_IsValid(int value) {
    return NrSlSciF1aHeaderProto_SciStage2Format_tProto_IsValid(value);
  }
  static constexpr SciStage2Format_tProto SciStage2Format_tProto_MIN =
    NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciStage2Format_tProto_MIN;
  static constexpr SciStage2Format_tProto SciStage2Format_tProto_MAX =
    NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciStage2Format_tProto_MAX;
  static constexpr int SciStage2Format_tProto_ARRAYSIZE =
    NrSlSciF1aHeaderProto_SciStage2Format_tProto_SciStage2Format_tProto_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  SciStage2Format_tProto_descriptor() {
    return NrSlSciF1aHeaderProto_SciStage2Format_tProto_descriptor();
  }
  template<typename T>
  static inline const std::string& SciStage2Format_tProto_Name(T enum_t_value) {
    static_assert(::std::is_same<T, SciStage2Format_tProto>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function SciStage2Format_tProto_Name.");
    return NrSlSciF1aHeaderProto_SciStage2Format_tProto_Name(enum_t_value);
  }
  static inline bool SciStage2Format_tProto_Parse(const std::string& name,
      SciStage2Format_tProto* value) {
    return NrSlSciF1aHeaderProto_SciStage2Format_tProto_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kSciFormatFieldNumber = 13,
    kMTotalSubChannelsFieldNumber = 1,
    kMPriorityFieldNumber = 2,
    kMIndexStartSubChannelFieldNumber = 3,
    kMLengthSubChannelFieldNumber = 4,
    kMMcsFieldNumber = 5,
    kMSlResourceReservePeriodFieldNumber = 6,
    kMSlMaxNumPerReserveFieldNumber = 7,
    kMSlSciStage2FormatFieldNumber = 8,
    kMIndexStartSbChReTx1FieldNumber = 9,
    kMIndexStartSbChReTx2FieldNumber = 10,
    kMGapReTx1FieldNumber = 11,
    kMGapReTx2FieldNumber = 12,
  };
  // repeated .ns3.NrSlSciF1aHeaderProto.SciStage2Format_tProto sciFormat = 13 [packed = true];
  int sciformat_size() const;
  private:
  int _internal_sciformat_size() const;
  public:
  void clear_sciformat();
  private:
  ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto _internal_sciformat(int index) const;
  void _internal_add_sciformat(::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* _internal_mutable_sciformat();
  public:
  ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto sciformat(int index) const;
  void set_sciformat(int index, ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto value);
  void add_sciformat(::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>& sciformat() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>* mutable_sciformat();

  // uint32 m_totalSubChannels = 1;
  void clear_m_totalsubchannels();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_totalsubchannels() const;
  void set_m_totalsubchannels(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_totalsubchannels() const;
  void _internal_set_m_totalsubchannels(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_priority = 2;
  void clear_m_priority();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_priority() const;
  void set_m_priority(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_priority() const;
  void _internal_set_m_priority(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_indexStartSubChannel = 3;
  void clear_m_indexstartsubchannel();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_indexstartsubchannel() const;
  void set_m_indexstartsubchannel(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_indexstartsubchannel() const;
  void _internal_set_m_indexstartsubchannel(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_lengthSubChannel = 4;
  void clear_m_lengthsubchannel();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_lengthsubchannel() const;
  void set_m_lengthsubchannel(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_lengthsubchannel() const;
  void _internal_set_m_lengthsubchannel(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_mcs = 5;
  void clear_m_mcs();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_mcs() const;
  void set_m_mcs(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_mcs() const;
  void _internal_set_m_mcs(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_slResourceReservePeriod = 6;
  void clear_m_slresourcereserveperiod();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_slresourcereserveperiod() const;
  void set_m_slresourcereserveperiod(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_slresourcereserveperiod() const;
  void _internal_set_m_slresourcereserveperiod(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_slMaxNumPerReserve = 7;
  void clear_m_slmaxnumperreserve();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_slmaxnumperreserve() const;
  void set_m_slmaxnumperreserve(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_slmaxnumperreserve() const;
  void _internal_set_m_slmaxnumperreserve(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_slSciStage2Format = 8;
  void clear_m_slscistage2format();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_slscistage2format() const;
  void set_m_slscistage2format(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_slscistage2format() const;
  void _internal_set_m_slscistage2format(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_indexStartSbChReTx1 = 9;
  void clear_m_indexstartsbchretx1();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_indexstartsbchretx1() const;
  void set_m_indexstartsbchretx1(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_indexstartsbchretx1() const;
  void _internal_set_m_indexstartsbchretx1(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_indexStartSbChReTx2 = 10;
  void clear_m_indexstartsbchretx2();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_indexstartsbchretx2() const;
  void set_m_indexstartsbchretx2(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_indexstartsbchretx2() const;
  void _internal_set_m_indexstartsbchretx2(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_gapReTx1 = 11;
  void clear_m_gapretx1();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_gapretx1() const;
  void set_m_gapretx1(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_gapretx1() const;
  void _internal_set_m_gapretx1(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 m_gapReTx2 = 12;
  void clear_m_gapretx2();
  ::PROTOBUF_NAMESPACE_ID::uint32 m_gapretx2() const;
  void set_m_gapretx2(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_m_gapretx2() const;
  void _internal_set_m_gapretx2(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:ns3.NrSlSciF1aHeaderProto)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField<int> sciformat_;
  mutable std::atomic<int> _sciformat_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_totalsubchannels_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_priority_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_indexstartsubchannel_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_lengthsubchannel_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_mcs_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_slresourcereserveperiod_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_slmaxnumperreserve_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_slscistage2format_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_indexstartsbchretx1_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_indexstartsbchretx2_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_gapretx1_;
  ::PROTOBUF_NAMESPACE_ID::uint32 m_gapretx2_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_sl_2dsci_2dmsg_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// NrSlMacPduTagProto_SfnSfProto

// uint32 m_frameNum = 1;
inline void NrSlMacPduTagProto_SfnSfProto::clear_m_framenum() {
  m_framenum_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto_SfnSfProto::_internal_m_framenum() const {
  return m_framenum_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto_SfnSfProto::m_framenum() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlMacPduTagProto.SfnSfProto.m_frameNum)
  return _internal_m_framenum();
}
inline void NrSlMacPduTagProto_SfnSfProto::_internal_set_m_framenum(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_framenum_ = value;
}
inline void NrSlMacPduTagProto_SfnSfProto::set_m_framenum(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_framenum(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlMacPduTagProto.SfnSfProto.m_frameNum)
}

// uint32 m_subframeNum = 2;
inline void NrSlMacPduTagProto_SfnSfProto::clear_m_subframenum() {
  m_subframenum_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto_SfnSfProto::_internal_m_subframenum() const {
  return m_subframenum_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto_SfnSfProto::m_subframenum() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlMacPduTagProto.SfnSfProto.m_subframeNum)
  return _internal_m_subframenum();
}
inline void NrSlMacPduTagProto_SfnSfProto::_internal_set_m_subframenum(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_subframenum_ = value;
}
inline void NrSlMacPduTagProto_SfnSfProto::set_m_subframenum(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_subframenum(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlMacPduTagProto.SfnSfProto.m_subframeNum)
}

// uint32 m_slotNum = 3;
inline void NrSlMacPduTagProto_SfnSfProto::clear_m_slotnum() {
  m_slotnum_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto_SfnSfProto::_internal_m_slotnum() const {
  return m_slotnum_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto_SfnSfProto::m_slotnum() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlMacPduTagProto.SfnSfProto.m_slotNum)
  return _internal_m_slotnum();
}
inline void NrSlMacPduTagProto_SfnSfProto::_internal_set_m_slotnum(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_slotnum_ = value;
}
inline void NrSlMacPduTagProto_SfnSfProto::set_m_slotnum(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_slotnum(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlMacPduTagProto.SfnSfProto.m_slotNum)
}

// uint32 m_numerology = 4;
inline void NrSlMacPduTagProto_SfnSfProto::clear_m_numerology() {
  m_numerology_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto_SfnSfProto::_internal_m_numerology() const {
  return m_numerology_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto_SfnSfProto::m_numerology() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlMacPduTagProto.SfnSfProto.m_numerology)
  return _internal_m_numerology();
}
inline void NrSlMacPduTagProto_SfnSfProto::_internal_set_m_numerology(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_numerology_ = value;
}
inline void NrSlMacPduTagProto_SfnSfProto::set_m_numerology(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_numerology(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlMacPduTagProto.SfnSfProto.m_numerology)
}

// -------------------------------------------------------------------

// NrSlMacPduTagProto

// uint32 m_rnti = 1;
inline void NrSlMacPduTagProto::clear_m_rnti() {
  m_rnti_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto::_internal_m_rnti() const {
  return m_rnti_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto::m_rnti() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlMacPduTagProto.m_rnti)
  return _internal_m_rnti();
}
inline void NrSlMacPduTagProto::_internal_set_m_rnti(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_rnti_ = value;
}
inline void NrSlMacPduTagProto::set_m_rnti(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_rnti(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlMacPduTagProto.m_rnti)
}

// uint32 m_symStart = 2;
inline void NrSlMacPduTagProto::clear_m_symstart() {
  m_symstart_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto::_internal_m_symstart() const {
  return m_symstart_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto::m_symstart() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlMacPduTagProto.m_symStart)
  return _internal_m_symstart();
}
inline void NrSlMacPduTagProto::_internal_set_m_symstart(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_symstart_ = value;
}
inline void NrSlMacPduTagProto::set_m_symstart(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_symstart(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlMacPduTagProto.m_symStart)
}

// uint32 m_numSym = 3;
inline void NrSlMacPduTagProto::clear_m_numsym() {
  m_numsym_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto::_internal_m_numsym() const {
  return m_numsym_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto::m_numsym() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlMacPduTagProto.m_numSym)
  return _internal_m_numsym();
}
inline void NrSlMacPduTagProto::_internal_set_m_numsym(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_numsym_ = value;
}
inline void NrSlMacPduTagProto::set_m_numsym(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_numsym(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlMacPduTagProto.m_numSym)
}

// uint32 m_tbSize = 4;
inline void NrSlMacPduTagProto::clear_m_tbsize() {
  m_tbsize_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto::_internal_m_tbsize() const {
  return m_tbsize_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto::m_tbsize() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlMacPduTagProto.m_tbSize)
  return _internal_m_tbsize();
}
inline void NrSlMacPduTagProto::_internal_set_m_tbsize(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_tbsize_ = value;
}
inline void NrSlMacPduTagProto::set_m_tbsize(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_tbsize(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlMacPduTagProto.m_tbSize)
}

// uint32 m_dstL2Id = 5;
inline void NrSlMacPduTagProto::clear_m_dstl2id() {
  m_dstl2id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto::_internal_m_dstl2id() const {
  return m_dstl2id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlMacPduTagProto::m_dstl2id() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlMacPduTagProto.m_dstL2Id)
  return _internal_m_dstl2id();
}
inline void NrSlMacPduTagProto::_internal_set_m_dstl2id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_dstl2id_ = value;
}
inline void NrSlMacPduTagProto::set_m_dstl2id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_dstl2id(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlMacPduTagProto.m_dstL2Id)
}

// .ns3.NrSlMacPduTagProto.SfnSfProto m_sfnSf = 6;
inline bool NrSlMacPduTagProto::_internal_has_m_sfnsf() const {
  return this != internal_default_instance() && m_sfnsf_ != nullptr;
}
inline bool NrSlMacPduTagProto::has_m_sfnsf() const {
  return _internal_has_m_sfnsf();
}
inline void NrSlMacPduTagProto::clear_m_sfnsf() {
  if (GetArena() == nullptr && m_sfnsf_ != nullptr) {
    delete m_sfnsf_;
  }
  m_sfnsf_ = nullptr;
}
inline const ::ns3::NrSlMacPduTagProto_SfnSfProto& NrSlMacPduTagProto::_internal_m_sfnsf() const {
  const ::ns3::NrSlMacPduTagProto_SfnSfProto* p = m_sfnsf_;
  return p != nullptr ? *p : *reinterpret_cast<const ::ns3::NrSlMacPduTagProto_SfnSfProto*>(
      &::ns3::_NrSlMacPduTagProto_SfnSfProto_default_instance_);
}
inline const ::ns3::NrSlMacPduTagProto_SfnSfProto& NrSlMacPduTagProto::m_sfnsf() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlMacPduTagProto.m_sfnSf)
  return _internal_m_sfnsf();
}
inline void NrSlMacPduTagProto::unsafe_arena_set_allocated_m_sfnsf(
    ::ns3::NrSlMacPduTagProto_SfnSfProto* m_sfnsf) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(m_sfnsf_);
  }
  m_sfnsf_ = m_sfnsf;
  if (m_sfnsf) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ns3.NrSlMacPduTagProto.m_sfnSf)
}
inline ::ns3::NrSlMacPduTagProto_SfnSfProto* NrSlMacPduTagProto::release_m_sfnsf() {
  auto temp = unsafe_arena_release_m_sfnsf();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::ns3::NrSlMacPduTagProto_SfnSfProto* NrSlMacPduTagProto::unsafe_arena_release_m_sfnsf() {
  // @@protoc_insertion_point(field_release:ns3.NrSlMacPduTagProto.m_sfnSf)
  
  ::ns3::NrSlMacPduTagProto_SfnSfProto* temp = m_sfnsf_;
  m_sfnsf_ = nullptr;
  return temp;
}
inline ::ns3::NrSlMacPduTagProto_SfnSfProto* NrSlMacPduTagProto::_internal_mutable_m_sfnsf() {
  
  if (m_sfnsf_ == nullptr) {
    auto* p = CreateMaybeMessage<::ns3::NrSlMacPduTagProto_SfnSfProto>(GetArena());
    m_sfnsf_ = p;
  }
  return m_sfnsf_;
}
inline ::ns3::NrSlMacPduTagProto_SfnSfProto* NrSlMacPduTagProto::mutable_m_sfnsf() {
  // @@protoc_insertion_point(field_mutable:ns3.NrSlMacPduTagProto.m_sfnSf)
  return _internal_mutable_m_sfnsf();
}
inline void NrSlMacPduTagProto::set_allocated_m_sfnsf(::ns3::NrSlMacPduTagProto_SfnSfProto* m_sfnsf) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete m_sfnsf_;
  }
  if (m_sfnsf) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(m_sfnsf);
    if (message_arena != submessage_arena) {
      m_sfnsf = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, m_sfnsf, submessage_arena);
    }
    
  } else {
    
  }
  m_sfnsf_ = m_sfnsf;
  // @@protoc_insertion_point(field_set_allocated:ns3.NrSlMacPduTagProto.m_sfnSf)
}

// -------------------------------------------------------------------

// NrSlSciF1aHeaderProto

// uint32 m_totalSubChannels = 1;
inline void NrSlSciF1aHeaderProto::clear_m_totalsubchannels() {
  m_totalsubchannels_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::_internal_m_totalsubchannels() const {
  return m_totalsubchannels_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::m_totalsubchannels() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_totalSubChannels)
  return _internal_m_totalsubchannels();
}
inline void NrSlSciF1aHeaderProto::_internal_set_m_totalsubchannels(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_totalsubchannels_ = value;
}
inline void NrSlSciF1aHeaderProto::set_m_totalsubchannels(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_totalsubchannels(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_totalSubChannels)
}

// uint32 m_priority = 2;
inline void NrSlSciF1aHeaderProto::clear_m_priority() {
  m_priority_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::_internal_m_priority() const {
  return m_priority_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::m_priority() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_priority)
  return _internal_m_priority();
}
inline void NrSlSciF1aHeaderProto::_internal_set_m_priority(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_priority_ = value;
}
inline void NrSlSciF1aHeaderProto::set_m_priority(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_priority(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_priority)
}

// uint32 m_indexStartSubChannel = 3;
inline void NrSlSciF1aHeaderProto::clear_m_indexstartsubchannel() {
  m_indexstartsubchannel_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::_internal_m_indexstartsubchannel() const {
  return m_indexstartsubchannel_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::m_indexstartsubchannel() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_indexStartSubChannel)
  return _internal_m_indexstartsubchannel();
}
inline void NrSlSciF1aHeaderProto::_internal_set_m_indexstartsubchannel(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_indexstartsubchannel_ = value;
}
inline void NrSlSciF1aHeaderProto::set_m_indexstartsubchannel(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_indexstartsubchannel(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_indexStartSubChannel)
}

// uint32 m_lengthSubChannel = 4;
inline void NrSlSciF1aHeaderProto::clear_m_lengthsubchannel() {
  m_lengthsubchannel_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::_internal_m_lengthsubchannel() const {
  return m_lengthsubchannel_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::m_lengthsubchannel() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_lengthSubChannel)
  return _internal_m_lengthsubchannel();
}
inline void NrSlSciF1aHeaderProto::_internal_set_m_lengthsubchannel(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_lengthsubchannel_ = value;
}
inline void NrSlSciF1aHeaderProto::set_m_lengthsubchannel(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_lengthsubchannel(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_lengthSubChannel)
}

// uint32 m_mcs = 5;
inline void NrSlSciF1aHeaderProto::clear_m_mcs() {
  m_mcs_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::_internal_m_mcs() const {
  return m_mcs_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::m_mcs() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_mcs)
  return _internal_m_mcs();
}
inline void NrSlSciF1aHeaderProto::_internal_set_m_mcs(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_mcs_ = value;
}
inline void NrSlSciF1aHeaderProto::set_m_mcs(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_mcs(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_mcs)
}

// uint32 m_slResourceReservePeriod = 6;
inline void NrSlSciF1aHeaderProto::clear_m_slresourcereserveperiod() {
  m_slresourcereserveperiod_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::_internal_m_slresourcereserveperiod() const {
  return m_slresourcereserveperiod_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::m_slresourcereserveperiod() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_slResourceReservePeriod)
  return _internal_m_slresourcereserveperiod();
}
inline void NrSlSciF1aHeaderProto::_internal_set_m_slresourcereserveperiod(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_slresourcereserveperiod_ = value;
}
inline void NrSlSciF1aHeaderProto::set_m_slresourcereserveperiod(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_slresourcereserveperiod(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_slResourceReservePeriod)
}

// uint32 m_slMaxNumPerReserve = 7;
inline void NrSlSciF1aHeaderProto::clear_m_slmaxnumperreserve() {
  m_slmaxnumperreserve_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::_internal_m_slmaxnumperreserve() const {
  return m_slmaxnumperreserve_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::m_slmaxnumperreserve() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_slMaxNumPerReserve)
  return _internal_m_slmaxnumperreserve();
}
inline void NrSlSciF1aHeaderProto::_internal_set_m_slmaxnumperreserve(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_slmaxnumperreserve_ = value;
}
inline void NrSlSciF1aHeaderProto::set_m_slmaxnumperreserve(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_slmaxnumperreserve(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_slMaxNumPerReserve)
}

// uint32 m_slSciStage2Format = 8;
inline void NrSlSciF1aHeaderProto::clear_m_slscistage2format() {
  m_slscistage2format_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::_internal_m_slscistage2format() const {
  return m_slscistage2format_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::m_slscistage2format() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_slSciStage2Format)
  return _internal_m_slscistage2format();
}
inline void NrSlSciF1aHeaderProto::_internal_set_m_slscistage2format(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_slscistage2format_ = value;
}
inline void NrSlSciF1aHeaderProto::set_m_slscistage2format(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_slscistage2format(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_slSciStage2Format)
}

// uint32 m_indexStartSbChReTx1 = 9;
inline void NrSlSciF1aHeaderProto::clear_m_indexstartsbchretx1() {
  m_indexstartsbchretx1_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::_internal_m_indexstartsbchretx1() const {
  return m_indexstartsbchretx1_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::m_indexstartsbchretx1() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_indexStartSbChReTx1)
  return _internal_m_indexstartsbchretx1();
}
inline void NrSlSciF1aHeaderProto::_internal_set_m_indexstartsbchretx1(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_indexstartsbchretx1_ = value;
}
inline void NrSlSciF1aHeaderProto::set_m_indexstartsbchretx1(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_indexstartsbchretx1(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_indexStartSbChReTx1)
}

// uint32 m_indexStartSbChReTx2 = 10;
inline void NrSlSciF1aHeaderProto::clear_m_indexstartsbchretx2() {
  m_indexstartsbchretx2_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::_internal_m_indexstartsbchretx2() const {
  return m_indexstartsbchretx2_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::m_indexstartsbchretx2() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_indexStartSbChReTx2)
  return _internal_m_indexstartsbchretx2();
}
inline void NrSlSciF1aHeaderProto::_internal_set_m_indexstartsbchretx2(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_indexstartsbchretx2_ = value;
}
inline void NrSlSciF1aHeaderProto::set_m_indexstartsbchretx2(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_indexstartsbchretx2(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_indexStartSbChReTx2)
}

// uint32 m_gapReTx1 = 11;
inline void NrSlSciF1aHeaderProto::clear_m_gapretx1() {
  m_gapretx1_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::_internal_m_gapretx1() const {
  return m_gapretx1_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::m_gapretx1() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_gapReTx1)
  return _internal_m_gapretx1();
}
inline void NrSlSciF1aHeaderProto::_internal_set_m_gapretx1(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_gapretx1_ = value;
}
inline void NrSlSciF1aHeaderProto::set_m_gapretx1(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_gapretx1(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_gapReTx1)
}

// uint32 m_gapReTx2 = 12;
inline void NrSlSciF1aHeaderProto::clear_m_gapretx2() {
  m_gapretx2_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::_internal_m_gapretx2() const {
  return m_gapretx2_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 NrSlSciF1aHeaderProto::m_gapretx2() const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.m_gapReTx2)
  return _internal_m_gapretx2();
}
inline void NrSlSciF1aHeaderProto::_internal_set_m_gapretx2(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  m_gapretx2_ = value;
}
inline void NrSlSciF1aHeaderProto::set_m_gapretx2(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_m_gapretx2(value);
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.m_gapReTx2)
}

// repeated .ns3.NrSlSciF1aHeaderProto.SciStage2Format_tProto sciFormat = 13 [packed = true];
inline int NrSlSciF1aHeaderProto::_internal_sciformat_size() const {
  return sciformat_.size();
}
inline int NrSlSciF1aHeaderProto::sciformat_size() const {
  return _internal_sciformat_size();
}
inline void NrSlSciF1aHeaderProto::clear_sciformat() {
  sciformat_.Clear();
}
inline ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto NrSlSciF1aHeaderProto::_internal_sciformat(int index) const {
  return static_cast< ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto >(sciformat_.Get(index));
}
inline ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto NrSlSciF1aHeaderProto::sciformat(int index) const {
  // @@protoc_insertion_point(field_get:ns3.NrSlSciF1aHeaderProto.sciFormat)
  return _internal_sciformat(index);
}
inline void NrSlSciF1aHeaderProto::set_sciformat(int index, ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto value) {
  sciformat_.Set(index, value);
  // @@protoc_insertion_point(field_set:ns3.NrSlSciF1aHeaderProto.sciFormat)
}
inline void NrSlSciF1aHeaderProto::_internal_add_sciformat(::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto value) {
  sciformat_.Add(value);
}
inline void NrSlSciF1aHeaderProto::add_sciformat(::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto value) {
  // @@protoc_insertion_point(field_add:ns3.NrSlSciF1aHeaderProto.sciFormat)
  _internal_add_sciformat(value);
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>&
NrSlSciF1aHeaderProto::sciformat() const {
  // @@protoc_insertion_point(field_list:ns3.NrSlSciF1aHeaderProto.sciFormat)
  return sciformat_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
NrSlSciF1aHeaderProto::_internal_mutable_sciformat() {
  return &sciformat_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField<int>*
NrSlSciF1aHeaderProto::mutable_sciformat() {
  // @@protoc_insertion_point(field_mutable_list:ns3.NrSlSciF1aHeaderProto.sciFormat)
  return _internal_mutable_sciformat();
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ns3

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto>() {
  return ::ns3::NrSlSciF1aHeaderProto_SciStage2Format_tProto_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_sl_2dsci_2dmsg_2eproto
